### ISSUE TITLE
aviasales.ru [Incorrect Domain Blocking]

### ISSUE THREAD

**Issue by dayAlone** [adblock-thai/thai-ads-filter#17]
Hello, can you remove the domain aviasales.ru from your [ad servers list](https://github.com/adblock-thai/thai-ads-filter/blob/dc032c9f103ae7342930aecd7437dc8af587b54b/filters/general/adservers_block.txt#L57)? 

Thai ads filter with the AdGuard browser extension causes malfunctioning of our web app.

**Comment by kowith337** [comment]
Sorry about that domain filter, because I've added a while ago in another filter that I've maintaining and rarely update due to some sites in Thai loves to inject more and more ads and tracking resources as much as they can to earn more revenue and benefits for them, because lots of sites are loaded through ads and tracking providers (include this one), first think in my head is it suspicious and why some foreign domains loaded and/or appeared in Thai sites for unclear and unrelated reasons except for advertisement and tracking purposes.

In case if it broke something, I will make a pull for this.

**Comment by dayAlone** [comment]
It's hard to tell without a proper example. 

We have an affiliate program and widgets that webmasters can embed on their website for additional monetization, but I'm not sure that blocking the whole domain is the proper way to prevent tracking.

Thank you for the pull request! 🙏
